import puppeteer from 'puppeteer';
const browser = await puppeteer.launch();
const page = await browser.newPage();
page.on('console', msg => console.log('LOG:', msg.text()));
page.on('pageerror', error => console.log('ERROR:', error.message));
page.on('requestfailed', request => console.log('REQUEST FAILED:', request.url(), request.failure().errorText));
await page.goto('http://localhost:4173', { waitUntil: 'networkidle0' });
await new Promise(r => setTimeout(r, 2000));
const content = await page.content();
console.log(content.substring(0, 500));
await browser.close();
